# Generated by Django 3.0.7 on 2020-06-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20200607_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='tables',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
