# Generated by Django 3.0.7 on 2020-06-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0009_auto_20200607_1126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('slug', 'restaurant')},
        ),
    ]
